include Include/BuildSystem/CommonDefs.mak

BIN_DIR = Bin

INC_DIRS = \
	Include \
	$(OPENNI2_INCLUDE)

SRC_FILES = *.cpp

LIB_DIRS += Bin

USED_LIBS += OpenNI2 NiTE2

EXE_NAME = UserTracker

CFLAGS += -Wall

include Include/BuildSystem/CommonCppMakefile
